config/routes.rb
Rails.application.routes.draw do
  resources :users
  resources :sessions
  resources :events do
    member do
      post 'attend'
      post 'withdraw'
    end
  end
  get    '/login',   to: 'sessions#new'
  post   '/login',   to: 'sessions#create'
  get '/logout',  to: 'sessions#destroy'
  post '/logout', to: 'sessions#destroy'
  get '/welcome', to: 'sessions#welcome'
  post '/welcome', to: 'sessions#welcome'
  root to: 'sessions#welcome'
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/Attendance.rb
class Attendance < ApplicationRecord
  belongs_to :event
  belongs_to :user
  validates :event_id, uniqueness: { scope: :user_id, message: 'You are already attending' }
end

app/models/User.rb
class User < ActiveRecord::Base
  validates :email, presence: true, uniqueness: true
  validates :name, presence: true
  has_many :events, dependent: :destroy
  has_many :attendances
  has_many :attended_events, through: :attendances, source: :event
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/attendance.rb
class Attendance < ApplicationRecord
  belongs_to :event
  belongs_to :user
  validates :event_id, uniqueness: { scope: :user_id, message: 'You are already attending' }
end

app/models/event.rb
class Event < ApplicationRecord
  validates :title, presence: true
  validates :date, presence: true
  belongs_to :creator, class_name: 'User'
  has_many :attendances
  has_many :attendees, through: :attendances, source: :user
  scope :past, -> { where('date < ?', Time.current) }
  scope :upcoming, -> { where('date > ?', Time.current) }
end

app/models/user.rb
class User < ActiveRecord::Base
  validates :email, presence: true, uniqueness: true
  validates :name, presence: true
  has_many :events, foreign_key: :creator_id, dependent: :destroy
  has_many :attendances
  has_many :attended_events, through: :attendances, source: :event
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  include SessionsHelper
end

app/controllers/events_controller.rb
class EventsController < ApplicationController
  def index
    @events = Event.all
  end

  def show
    @event = Event.find(params[:id])
  end

  def new
    @event = current_user.events.build
  end

  def create
    @event = current_user.events.build(event_params)
    respond_to do |format|
      if @event.save
        format.html { redirect_to @event, notice: 'Event was successfully created.' }
        format.json { render :show, status: :created, location: @event }
      else
        format.html { render :new }
        format.json { render json: @event.errors, status: :unprocessable_entity }
      end
    end
  end

  def attend
    @event = Event.find(params[:id])
    @event.attendees << current_user
    @event.save!
    redirect_to event_path(@event)
  end

  def withdraw
    @event = Event.find(params[:id])
    @event.attendees.delete(current_user)
    @event.save!
    redirect_to event_path(@event)
  end

  private

  def event_params
    params.require(:event).permit(:title, :description, :date)
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  include SessionsHelper
  def new; end

  def create
    @user = User.find_by(email: params[:email])
    if @user
      reset_session
      log_in @user
      redirect_to '/welcome'
    else
      redirect_to '/login'
    end
  end

  def login; end

  def welcome; end

  def destroy
    log_out
    redirect_to '/welcome'
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  include SessionsHelper

  # GET /users
  # GET /users.json
  def index
    @users = User.all
  end

  # GET /users/1
  # GET /users/1.json
  def show
    @user = User.find(params[:id])
    @user_upcoming_events = @user.events.where('date > ?', Time.current)
    @user_past_events = @user.events.where('date < ?', Time.current)
    @user_attended_upcoming = @user.attended_events.where('date > ?', Time.current)
    @user_attended_past = @user.attended_events.where('date < ?', Time.current)
  end

  # GET /users/new
  def new
    @user = User.new
  end

  # GET /users/1/edit
  def edit; end

  # POST /users
  # POST /users.json
  def create
    @user = User.new(user_params)
    if @user.save
      reset_session
      log_in @user
      flash[:success] = 'Welcome!'
      redirect_to @user
    else
      redirect_to '/welcome'
    end
  end

  # PATCH/PUT /users/1
  # PATCH/PUT /users/1.json
  def update
    respond_to do |format|
      if @user.update(user_params)
        format.html { redirect_to '/welcome', notice: 'User was successfully updated.' }
        format.json { render :show, status: :ok, location: @user }
      else
        format.html { render :edit }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /users/1
  # DELETE /users/1.json
  def destroy
    @user.destroy
    respond_to do |format|
      format.html { redirect_to users_url, notice: 'User was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private

  # Use callbacks to share common setup or constraints between actions.
  def set_user
    @user = User.find(params[:id])
  end

  # Only allow a list of trusted parameters through.
  def user_params
    params.require(:user).permit(:name, :email)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
  include SessionsHelper
end

app/helpers/events_helper.rb
module EventsHelper
  def attending(event)
    return nil unless logged_in?

    if event.attendees.include? current_user
      button_to 'Withdraw', withdraw_event_path(@event), method: :post
    else
      button_to 'Attend', attend_event_path(@event), method: :post
    end
  end
end

app/helpers/sessions_helper.rb
module SessionsHelper
  def current_user
    User.find_by(id: session[:user_id]) if session[:user_id]
  end

  def logged_in?
    !current_user.nil?
  end

  def log_in(user)
    session[:user_id] = user.id
  end

  def log_out
    reset_session
    @current_user = nil
  end

  def headers
    if logged_in?
      'header-user'
    else
      'header-guest'
    end
  end
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/events/attend.html.erb
thank you!

app/views/events/create.html.erb
<h1>Events#create</h1>

app/views/events/index.html.erb
<%= render "shared/header"%>

<h1>Upcoming Events</h1>
<% @events.upcoming.each do | event | %>
    <div class="box">
        <article class="media">
            <div class="media-left">
                <figure class="image is-64x64">
                    <img src="https://bulma.io/images/placeholders/64x64.png" alt="">
                </figure>
            </div>   
            <div class="media-content">
                <div class="content">
                <strong><%= link_to event.title, event_path(event.id) %></strong><br />
                <small><%= event.description %></small><br />
                <small><%= event.date %></small><br />
                <p><%= link_to event.creator.name, user_path(event.creator.id) %></p>
                </div>
            </div>
        </article>
    </div>
    
<% end %>

<h1>Past Events</h1>
<% @events.past.each do | event | %>
    <div class="box">
        <article class="media">
            <div class="media-left">
                <figure class="image is-64x64">
                    <img src="https://bulma.io/images/placeholders/64x64.png" alt="">
                </figure>
            </div>   
            <div class="media-content">
                <div class="content">
                <strong><%= link_to event.title, event_path(event.id) %></strong><br />
                <small><%= event.description %></small><br />
                <small><%= event.date %></small><br />
                <p><%= link_to event.creator.name, user_path(event.creator.id) %></p>
                </div>
            </div>
        </article>
    </div>
    
<% end %>

app/views/events/new.html.erb
<%= render "shared/header"%>

<%= form_with(model: @event) do |form| %>
  <div class="field">
    <%= form.label :title %>
    <%= form.text_field :title %>
  </div>

  <div class="field">
    <%= form.label :description %>
    <%= form.text_area(:description, size: "50x10") %>
  </div>

  <div class="field date-of-event">
    <%= form.label :date %>
    <%= form.datetime_select :date %>
  </div>

  <div class="actions">
    <%= form.submit%>
  </div>
<% end %>

app/views/events/show.html.erb
<%= render "shared/header"%>

<h1>
  <strong>Title:</strong>
  <%= @event.title%>
</h1>

<p>
  <strong>Description:</strong>
  <%= @event.description %>
</p>

<p>
  <strong>Creator:</strong>
  <%= @event.creator.name %>
</p>

<p>
  <strong>Date:</strong>
  <%= @event.date %>
</p>


<h1>Attending:</h1>
<% @event.attendees.each do |attendee| %>

  <div class="content">
    <small><%= attendee.name %></small><br />
    <small><%= attendee.email %></small><br />
  </div>

<% end %>

<%= attending(@event) %>

<%= link_to 'Back', events_path %>

app/views/events/withdraw.html.erb
You've withdrawn from event.

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>PrivateEvents</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/shared/_header-guest.html.erb
<%= button_to "Login", '/login', method: :get%>
<%= button_to "Sign Up", '/users/new', method: :get%>

app/views/shared/_header-user.html.erb
<h1>What's Up, <%= link_to "#{current_user.name}", "/users/#{current_user.id}" %></h1>
<%= link_to "Logout", '/logout', method: :destroy%>

app/views/shared/_header.html.erb
<%= render "shared/#{headers}"%>
<span><%= link_to "Events", events_path %></span>
<span><%= link_to "Users", users_path %></span>

app/views/users/_form.html.erb
<%= form_with(model: user, local: true) do |form| %>

  <div class="field">
    <%= form.label :name %>
    <%= form.text_field :name %>
  </div>

  <div class="field">
    <%= form.label :email %>
    <%= form.text_field :email %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/users/edit.html.erb
<h1>Editing User</h1>

<%= render 'form', user: @user %>

<%= link_to 'Show', @user %> |
<%= link_to 'Back', users_path %>

app/views/users/index.html.erb
<p id="notice"><%= notice %></p>

<%= render "shared/header"%>

<h1>Users</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Email</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @users.each do |user| %>
      <tr>
        <td><%= user.name %></td>
        <td><%= user.email %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= button_to 'Welcome Page', '/welcome'%>

app/views/users/new.html.erb
<h1>New User</h1>

<%= render 'form', user: @user %>

<%= link_to 'welcome' %>

app/views/users/show.html.erb
<%= render "shared/header"%>

<p id="notice"><%= notice %></p>

<h1>
  <strong>Name:</strong>
  <%= @user.name %>
</h1>

<h2>
  <strong>Email:</strong>
  <%= @user.email %>
</h2>

<%= link_to "Create New Event", new_event_path %>

<h1>User's Events</h1>

<h3>Upcoming Events</h3>

<% @user_upcoming_events.each do | event | %>
    <div class="box">
        <article class="media">
            <div class="media-left">
                <figure class="image is-64x64">
                    <img src="https://bulma.io/images/placeholders/64x64.png" alt="">
                </figure>
            </div>   
            <div class="media-content">
                <div class="content">
                <strong><%= event.title %></strong><br />
                <small><%= event.description %></small><br />
                <small><%= event.date %></small><br />
                <p><%= event.creator.name %></p>
                </div>
            </div>
        </article>
    </div>   
<% end %>

<h3>Past Events</h3>

<% @user_past_events.each do | event | %>
    <div class="box">
        <article class="media">
            <div class="media-left">
                <figure class="image is-64x64">
                    <img src="https://bulma.io/images/placeholders/64x64.png" alt="">
                </figure>
            </div>   
            <div class="media-content">
                <div class="content">
                <strong><%= event.title %></strong><br />
                <small><%= event.description %></small><br />
                <small><%= event.date %></small><br />
                <p><%= event.creator.name %></p>
                </div>
            </div>
        </article>
    </div>  
<% end %>

<h1>Attended Events</h1>

<h3>Upcoming Events You're Attending</h3>

<% @user_attended_upcoming.each do | att_event | %>
    <div class="box">
        <article class="media">
            <div class="media-left">
                <figure class="image is-64x64">
                    <img src="https://bulma.io/images/placeholders/64x64.png" alt="">
                </figure>
            </div>   
            <div class="media-content">
                <div class="content">
                <strong><%= link_to att_event.title, event_path(att_event.id) %></strong><br />
                <small><%= att_event.description %></small><br />
                <small><%= att_event.date %></small><br />
                <p><%= link_to att_event.creator.name, user_path(att_event.creator.id) %></p>
                </div>
            </div>
        </article>
    </div>
<% end %>

<h3>Past Events You've Attended</h3>

<% @user_attended_past.each do | att_event | %>
    <div class="box">
        <article class="media">
            <div class="media-left">
                <figure class="image is-64x64">
                    <img src="https://bulma.io/images/placeholders/64x64.png" alt="">
                </figure>
            </div>   
            <div class="media-content">
                <div class="content">
                <strong><%= link_to att_event.title, event_path(att_event.id) %></strong><br />
                <small><%= att_event.description %></small><br />
                <small><%= att_event.date %></small><br />
                <p><%= link_to att_event.creator.name, user_path(att_event.creator.id) %></p>
                </div>
            </div>
        </article>
    </div>
<% end %>


<%= link_to 'Edit', edit_user_path(@user) %> |
<%= link_to 'Back', users_path %>